name: hackage-grep
version: 0.1.0.0

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - aeson
    - base
    - conduit
    - http-client
    - http-types
    - text
    - unliftio

executable:
  main: exe/Main.hs
  dependencies:
    - base
    - conduit
    - hackage-grep
    - optparse-applicative
    - text
