name: hackage-grep
version: 0.1.0.0

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - aeson
    - base
    - bytestring
    - conduit
    - http-client
    - http-client-tls
    - http-types
    - tagsoup
    - tar
    - text
    - unliftio
    - zlib

executable:
  main: exe/Main.hs
  dependencies:
    - base
    - conduit
    - hackage-grep
    - optparse-applicative
    - text
